server:
  port: 8080      

spring:
  main:
    show_banner: false
    banner-mode: "off"
  application:
    name: soapgateway
  datasource: 
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:data/derby/soapdata;create=true;user=system;password=agf@392
    username: system
    password: agf@392
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.DerbyTenSevenDialect